test-go:
    stage: test
    image: golang
    script:
        - go get -u golang.org/x/lint/golint
        - golint
        - go vet
        - go test -bench=. -benchmem -cover -short -v
    coverage: '/coverage: \d+\.\d+%/'
